//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListWebServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TO_DO_LISTEntities : DbContext
    {
        public TO_DO_LISTEntities()
            : base("name=TO_DO_LISTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOARD> BOARD { get; set; }
        public virtual DbSet<REL_TICKET_HAS_STATUS> REL_TICKET_HAS_STATUS { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }

        
    }
}
