//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListWebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_TICKET_HAS_STATUS
    {
        public long id_ticket { get; set; }
        public long id_status { get; set; }
        public System.DateTime date { get; set; }
        public long id { get; set; }
    
        public virtual STATUS STATUS { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
