//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListWebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKET()
        {
            this.REL_TICKET_HAS_STATUS = new HashSet<REL_TICKET_HAS_STATUS>();
        }
    
        public long id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int estimated_time { get; set; }
        public long board_id { get; set; }
    
        public virtual BOARD BOARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_TICKET_HAS_STATUS> REL_TICKET_HAS_STATUS { get; set; }
    }
}
